name: Create PFD
permissions:
  issues: write
on:
  push:
    branches: 
    - main
jobs:
  create-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: mkrakowitzer/actions-makepdfs@v1.3
      with:
    # Location of markdown files in github repository
        markdown_dir: /
    # Location to output PDF files to
        output_dir: /
          
